server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://ep-damp-fire-a4ujpbrj-pooler.us-east-1.aws.neon.tech:5432/AssesmentTorneos?sslmode=require
    username: neondb_owner
    password: npg_fui9THMJBo5m

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:mi_super_secret_ultra_seguro_1234567890}
  expiration: 3600000